#########################################################################################################################################
#       Application KTCARDS
#########################################################################################################################################

services:

  back_ktcards:
    container_name: back_ktcards
    image: back_ktcards:local
    env_file: .env
    environment:
      ConnectionStrings__Default: server=mariadb_ktcards;port=3306;database=ktcards;user=${KTCARDS_DB_USER};password=${KTCARDS_DB_PASSWORD};
      ASPNETCORE_URLS: "http://+:8080"
    restart: always
    depends_on:
      mariadb_ktcards:
        condition: service_healthy


  front_ktcards:
    container_name: front_ktcards
    image: front_ktcards:local
    ports:
      - "81:80"
    restart: always
    depends_on:
      - back_ktcards


  mariadb_ktcards:
    container_name: mariadb_ktcards
    image: mariadb:lts
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${KTCARDS_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ktcards
      MYSQL_USER: ${KTCARDS_DB_USER}
      MYSQL_PASSWORD: ${KTCARDS_DB_PASSWORD}
    volumes:
      - /opt/docker/data/_ktcards/mariadb_ktcards:/var/lib/mysql
      - ./scripts/mariadb_init:/docker-entrypoint-initdb.d:ro
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
