server 
{

	listen	80;

	server_name ktcards.ru;
	resolver 8.8.8.8;

	client_max_body_size 20M;

	location / 
	{
		root   /usr/share/nginx/html;
		index  index.html index.htm;
		try_files $uri $uri/ /index.html;
		add_header Cross-Origin-Opener-Policy "same-origin-allow-popups";
	}


	location /api 
	{
		proxy_pass http://ktcards:8080;
	}

	location /uploads
	{
		proxy_pass http://ktcards:8080;
	}




}